export const API_ENDPOINS = {
  SIGN_UP: "/auth/register/",
  OTP_VERIFICATION: "/auth/otp-verification/",
  LOGIN: "/auth/login/",
  UPAZILA_NAME: "/auth/upazila-name",
  FORGOT_PASSWORD_OTP: "/auth/forgot-password-otp/",
  FORGOT_PASSWORD: "/auth/save-password/",
  ONE_TIME_OTP: "/auth/one-time-otp/",
  RESEND_OTP: "/auth/resend-otp/",
  USER_INFO: "/auth/personal-info/",
  UPDATE_PROFILE: "/auth/update-personal-info/",
  CREATE_ANNOUNCEMENT: "/anc/create-announcement/",
  GET_ANNOUNCEMENTS: "/anc/own-announcement-list/",
  UPDATE_QUIZCARD: "/anc/edit-announcement/",
  QUIZCARD_ACTIVE: "/anc/active-announcement/",
  QUIZCARD_INACTIVE: "/anc/in-active-announcement/",
  ANNOUNCEMENT_LIST: "/anc/announcement-list-lp",
  OWN_DATA: "/anc/single-announcement-details/",
  INACTIVE_ANNOUNCEMENT_LIST: "/anc/in-active-announcement-list-lp",
  CLOSED_QUIZ: "/anc/closed-anc-list-lp/",
};
